#version 450
#extension GL_GOOGLE_include_directive : require
layout(constant_id = 0) const uint ELEMENT_BYTES = 4u;
layout(constant_id = 1) const uint TILE = 0u;
const uint BLOCK_BYTES = 65536u;
uvec3 block_extent() {
	uint width = ELEMENT_BYTES <= 2 ? 256u : 128u;
	return uvec3(width, BLOCK_BYTES / (width * ELEMENT_BYTES), 1u);
}
uint block_offset(uvec3 p) {
	uint x = p.x, y = p.y;
	uint z = ((p.z & 8u) << 5) ^ ((p.z & 4u) << 7) ^
	         ((p.z & 2u) << 9) ^ ((p.z & 1u) << 11);
	switch (ELEMENT_BYTES) {
	case 1: return z ^ (x & 0x0001u) ^ ((x << 1) & 0x0104u) ^
	               ((x << 2) & 0x0010u) ^ ((x << 3) & 0x0040u) ^
	               ((x << 4) & 0x0400u) ^ ((x << 5) & 0x0200u) ^
	               ((x << 6) & 0x1800u) ^ ((x << 7) & 0xc000u) ^
	               ((y << 1) & 0x0102u) ^ ((y << 2) & 0x0008u) ^
	               ((y << 3) & 0x0020u) ^ ((y << 4) & 0x0180u) ^
	               ((y << 5) & 0x0e00u) ^ ((y << 6) & 0x4000u) ^
	               ((y << 7) & 0x2000u) ^ ((y << 8) & 0x8000u);
	case 2: return z ^ ((x << 1) & 0x0102u) ^ ((x << 2) & 0x0008u) ^
	               ((x << 3) & 0x0020u) ^ ((x << 4) & 0x0480u) ^
	               ((x << 5) & 0x0200u) ^ ((x << 6) & 0x0800u) ^
	               ((x << 7) & 0xe000u) ^ ((y << 1) & 0x0100u) ^
	               ((y << 2) & 0x0004u) ^ ((y << 3) & 0x0010u) ^
	               ((y << 4) & 0x0140u) ^ ((y << 5) & 0x0e00u) ^
	               ((y << 7) & 0x4000u) ^ ((y << 9) & 0x9000u);
	case 4: return z ^ ((x << 1) & 0x0100u) ^ ((x << 2) & 0x0004u) ^
	               ((x << 3) & 0x0010u) ^ ((x << 4) & 0x0440u) ^
	               ((x << 5) & 0x0200u) ^ ((x << 6) & 0x0800u) ^
	               ((x << 8) & 0xc000u) ^ ((x << 9) & 0x1000u) ^
	               ((y << 1) & 0x0100u) ^ ((y << 3) & 0x0008u) ^
	               ((y << 4) & 0x0120u) ^ ((y << 5) & 0x0e80u) ^
	               ((y << 7) & 0x4000u) ^ ((y << 9) & 0x8000u) ^
	               ((y << 10) & 0x2000u);
	default: return z ^ ((x << 1) & 0x0100u) ^ ((x << 3) & 0x0008u) ^
	                ((x << 4) & 0x0420u) ^ ((x << 5) & 0x0280u) ^
	                ((x << 6) & 0x0800u) ^ ((x << 7) & 0x4000u) ^
	                ((x << 9) & 0x8000u) ^ ((x << 10) & 0x2000u) ^
	                ((y << 1) & 0x0100u) ^ ((y << 4) & 0x0110u) ^
	                ((y << 5) & 0x0e40u) ^ ((y << 9) & 0x8000u) ^
	                ((y << 10) & 0x1000u) ^ ((y << 11) & 0x4000u);
	}
}
#include "gpu_tiler_common.inc"
